/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_k_testandroid_Test */

#ifndef _Included_com_k_testandroid_Test
#define _Included_com_k_testandroid_Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_k_testandroid_Test
 * Method:    test
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_k_testandroid_Test_test
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
