/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdio.h>
#include <com_k_testandroid_Test.h>
/*
 * Class:     com_k_testandroid_Test
 * Method:    test
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_k_testandroid_Test_test
  (JNIEnv * env, jobject obj){
	return (*(*env)).NewStringUTF(env,"hello from c，你好");
}

